# -*- coding: utf-8 -*-
"""DRF_Funcs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oyJEvAivfl22o5YFjYGPR4luQIXCuPm7
"""

def drf_f1(discrepancy):
    delta = abs(discrepancy)

    if 0 <= delta <=1 :
        return 0  # indifference

    elif 1 < delta <= 2:
        return delta-1 # assimilation (y = x-1)

    elif 2 < delta <= 3:
        return 1 # assimilation (y = 1)

    elif 3 < delta <= 3.2:
        return -2*delta + 7 # assimilation (y=−2x+7)

    elif 3.2 < delta < 4:
        return 0  # ambivalence

    elif 4 <= delta < 5:
        return -1  # backfire

    elif 5 <= delta < 6:
        return  delta - 6 # backfire

    elif 6 <= delta  :
        return 0  # irrelevance (ignored)

def drf_inchworm_withso(discrepancy):
    delta = abs(discrepancy)

    if 0 <= delta < 2:
        return 0  # indifference

    elif 2 <= delta < 4:
        return 1  # assimilation (pull closer)

    elif 4 <= delta < 6:
        return -1  # backfire (push away)

    elif 6 <= delta  :
        return 0  # irrelevance (ignored)

    elif delta <= 2:
        return 0  # ambivalence

def drf_inc_noso(discrepancy):
    delta = abs(discrepancy)

    if 0 == delta:
        return 0  # indifference

    elif 0 < delta < 3:
        return 1  # assimilation (pull closer)

    elif 3 <= delta < 10:
        return -1  # backfire (push away)

    elif 10 <= delta  :
        return 0  # irrelevance (ignored)

    elif delta == 0:
        return 0  # ambivalence